swagger: '2.0'
info:
  version: 1.0.0


x-ads-service:
  - core-entity-version: 1.0.0
  - security-definition-version: 1.0.0
  - host-version: 1.0.0
    
x-ads-apiproxy:
  name: Acm 
  api_proxy: acm


x-ads-ratelimit:
  targets:

paths:

 

	
